# Generated by Django 5.2 on 2025-05-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redirects", "0003_redirect_created_at_redirect_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirect",
            name="new_path",
            field=models.CharField(
                blank=True,
                help_text=(
                    "This can be either an absolute path, an absolute URL, or a regex. "
                    'If empty a "410 Gone" response will be returned.'
                ),
                max_length=2048,
                verbose_name="New path",
            ),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="old_path",
            field=models.CharField(
                db_index=True,
                help_text=(
                    "This can be either an absolute path or a regex "
                    "(excluding the domain name). "
                ),
                max_length=2048,
                verbose_name="Old path",
            ),
        ),
    ]
