# Generated by Django 5.2.4 on 2025-07-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redirects", "0004_alter_redirect_new_path_alter_redirect_old_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="redirect",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Helpful notes reminding us why this redirect exists",
                verbose_name="Notes",
            ),
        ),
    ]
